png("plot4.png")
par(mfrow=c(2,2))
with(sdata,plot(wh[1:2880],Global_active_power,type="l",col="black",ylab="Global Active Power",xlab=""))
with(sdata,plot(wh[1:2880],Voltage,type="l",col="black",ylab="Voltage",xlab="datetime"))
with(sdata,plot(wh[1:2880],Sub_metering_1,type="l",col="black",ylab="Energy Sub Metering",xlab=""))
with(sdata,points(wh[1:2880],Sub_metering_2,type="l",col="red"))
with(sdata,points(wh[1:2880],Sub_metering_3,type="l",col="blue"))
legend("topright",col=c("black","red","blue"),bty="n",pch="_",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(sdata,plot(wh[1:2880],Global_reactive_power,type="l",col="black",ylab="Global_reactive_power",xlab="datetime"))
dev.off()